# Generated by Django 5.2.5 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyrescue',
            name='login_id',
        ),
        migrations.AddField(
            model_name='emergencyrescue',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emergencyrescue',
            name='status',
            field=models.CharField(choices=[('Varified', 'Varified'), ('Not Varified', 'Not Varified')], default='Not Varified', max_length=16),
        ),
    ]
