# Generated by Django 5.2.5 on 2025-10-15 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_complaint_user_id_remove_news_reporter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
