# Generated by Django 5.2.5 on 2025-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_volunteer_password_volunteer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
