# Generated by Django 5.2.5 on 2025-10-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_volunteer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=100),
        ),
    ]
