# Generated by Django 5.2.5 on 2025-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_needs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=100),
        ),
    ]
