# Generated by Django 5.2.5 on 2025-10-18 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_medicine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrescue',
            name='password',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyrescue',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
