# Generated by Django 6.0.3 on 2026-03-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_news_date_alter_news_image_alter_news_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('latitude', models.CharField(default=0, max_length=100)),
                ('longitude', models.CharField(default=0, max_length=100)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonateGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='Not Collected', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News_reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('chanelname', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='login_id',
        ),
        migrations.AlterField(
            model_name='camp',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='camp',
            name='total_member',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='emergency_rescue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emergencyrescue'),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyrescue',
            name='status',
            field=models.CharField(default='Not Varified', max_length=16),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='guideline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='priority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='needs',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='needs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='needs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='needs',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='needs',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='servicetype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinator'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='donategoods',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camp'),
        ),
        migrations.AddField(
            model_name='donategoods',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer'),
        ),
        migrations.AddField(
            model_name='news',
            name='NEWS_REPORTER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.news_reporter'),
        ),
        migrations.AddField(
            model_name='donategoods',
            name='Public',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.public'),
        ),
        migrations.AddField(
            model_name='collection',
            name='PUBLIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.public'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='PUBLIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.public'),
        ),
    ]
